# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: #select at which even the code below should be executed
  push: #run every time there's a direct push to master branch
    branches: [ "master" ,"Khing"]

  pull_request: #and run every time there's a pull request to master branch 
    branches: [ "master","Khing"] #--> make sure the incoming code doesn't break anything in the master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup JDK 17
      uses: actions/setup-java@v1
      with:
            java-version: 17
    - name: Build Project Hello Aj Ehsan
      run: gradle build

    - name: Running tests How are you doing Ajarn
      run: gradle :app:test --tests "softwareTestingProject.*"



